package com.team.cn.mapper;

import com.team.cn.entity.UserEntity;

public interface UserEntityMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    int insertSelective(UserEntity record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    UserEntity selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table police_admin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserEntity record);
}